Fix GH Action

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -34,7 +34,8 @@ jobs:
         STATUS=0
         for src_file in pandas_alchemy/*.py; do
           yapf "$src_file" > "$TMP_FILE"
-          if diff -u "$src_file" "$TMP_FILE"; then
+          if ! diff -u --color=always "$src_file" "$TMP_FILE"; then
+            echo "[ERROR] File $src_file does not conform to YAPF style"
             STATUS=1
           fi
         done
